version: 1.0.{build}
image: Visual Studio 2017
install:
- cmd: dotnet restore
build_script:
- cmd: dotnet build
test_script:
- cmd: dotnet test LuaValues.Csharp.Tests/LuaValues.Csharp.Tests.csproj